services:
  asistente-ia:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"  
    volumes:
      - .:/app
      - chroma_data:/app/db_data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  interfaz:
    build: .
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - asistente-ia
    environment:
      - API_URL=http://asistente-ia:8000

volumes:
  chroma_data: